name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # Weekly on Tuesday at 12:00 PM
    - cron: "0 12 * * 2"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-image:
    uses: rsturla-cloud/actions/.github/workflows/build-image.yml@0dedc89fa394bd3641f616237f2100107fe0b13e # main
    with:
      spec_file_path: ./image.yml
